package com.snakeio.snake.payload;


import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class PlayerRequestPayload {
    private String id;

    // Constructors, getters and setters can be generated by Lombok或手动实现
}
