package com.snakeio.snake.payload;

import com.snakeio.snake.model.Player;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@Data
public class PlayerMovePayload {
    private String id;
    private String type;
    private Player.Segment head;
    private long timestamp;

    // Constructors, getters and setters can be generated by Lombok或手动实现
}
